# MRAPRGUILD Termux interface settings
extra-keys = [['ESC','CTRL','ALT','TAB','HOME','UP','END'],['BKSP','LEFT','DOWN','RIGHT','PGUP','PGDN','ENTER']]
extra-keys-text-all-caps = false
terminal-cursor-style = bar
terminal-cursor-blink-rate = 600
bell-character = vibrate
use-black-ui = true
fullscreen = false
